<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Shwetha" ignored="0" name="Testme" tests="2" failures="1" timestamp="28 Sep 2018 08:27:26 GMT" time="18.788" errors="0">
  <testcase name="testA" time="0.578" classname="script.TestDemo">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at script.TestDemo.testA(TestDemo.java:21)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- testA -->
  <testcase name="testB" time="0.005" classname="script.TestDemo2"/>
</testsuite> <!-- Testme -->
